### ISSUE TITLE
[CSS] Use partials for modular CSS architecture?

### ISSUE THREAD

**Issue by giacomovergnano** [wikimedia/WikimediaUI-Style-Guide#365]
Hello all! (Hello again Volker 😄  )
I was checking the Style-guide's CSS structure. I see that there is just one partial folder for the font files and I was wondering if you had discussed the possibility of having a modular CSS file structure and decided against it.
If not I can open a pull request with my proposal and the reasoning behind it.

Thank you and all the best!

**Comment by giacomovergnano** [comment]
2. I would also like to add a second questions if I may. It would be beneficial to use a static web generator in order to avoid repetition in HTML code for shared components such as header, footer, sidebar, etc
Have you already decided against it, or are you open to a possible implementation? If so I could open another Pull Request with my edits

**Comment by Volker-E** [comment]
Hey @giacomovergnano, good to see you again!
Changing to a modular structure currently hasn't provided a strong enough, convincing benefit, given that we've also have, due to certain restrictions, other projects buidling on the main CSS prrovided here.

What were the arguments for a change from your perspective?

To your second point, yes. At length discussed in https://phabricator.wikimedia.org/T164449 but de-prioritized for other goals.
If you're interested, please participate in the discussion on Phabricator.

**Comment by giacomovergnano** [comment]
Hi @Volker-E thank you for your reply!
Point 1:
I was suggesting it because the setup of the Styleguide already allows it and from a maintainability and code navigation point of view I always have found easier to have different CSS modules for different utilities or style categories.
Indeed in the Styleguide case the code base is limited so the value might not be massive but for the same reason it makes it quite easy to implement at the moment.
Point 2:
Thank you for sharing the discussion, now I see it has indeed been discussed **at length** 😄 
I will read through it.

Thank you and all the best!

Giacomo

**Comment by Volker-E** [comment]
We might pick this proposal up in future again, closing currently for lack of priority, resources versus clear benefit on further development vs other pressing issues.
