### ISSUE TITLE
Buttons look wrong in Firefox

### ISSUE THREAD

**Issue by Nikerabbit** [wikimedia/WikimediaUI-Style-Guide#420]
This page https://design.wikimedia.org/style-guide/components/buttons.html looks like this on Firefox:
![image](https://user-images.githubusercontent.com/1109395/103627222-fd8ac580-4f45-11eb-8b6c-23bf3fbc5a7e.png)

On Chrome it looks as expected.

**Comment by reetssydney** [comment]
Hi @Nikerabbit - I can't reproduce this on my Firefox (84.0.1 (64-bit)) - would you mind refreshing and checking again? 
It's a little strange since the entire set of buttons is one image, not code.
![image](https://user-images.githubusercontent.com/7241063/103631117-e1d1f000-4f42-11eb-8e30-41a82fe0dd0a.png)

**Comment by Nikerabbit** [comment]
Refresh or private mode does not fix the issue. The issue is also present in https://design.wikimedia.org/style-guide/img/components/buttons_normal_and_primary_states.svg.

Maybe an SVG rendering issue in Firefox 78.6.0esr (Linux).

**Comment by reetssydney** [comment]
Ah, I think you're right about it being an issue with SVG rendering. I didn't realise till now that the button text is being rendered as SVG <text> elements instead of as fills, and for whatever reason its rendering the font differently with greater letter-spacing than expected in certain browsers. 
Here's an example with the font larger with more letter-space on one element which replicates your issue. ![image](https://user-images.githubusercontent.com/7241063/103645718-c7a30c80-4f58-11eb-93f6-7acb70bf0214.png)
 
I've created new svgs with text outlined, though these are 4-6x larger in file size, and there may well be other reasons why @Volker-E would want to keep it to SVG text. However, it will be good to know first if this is solves the issue. 

Can you open and see if these render correctly:
**[button svgs text outlined.zip](https://github.com/wikimedia/WikimediaUI-Style-Guide/files/5770107/button.svgs.text.outlined.zip)**

**Comment by Nikerabbit** [comment]
I can confirm that the outlined versions render as expected in my Firefox.

**Comment by reetssydney** [comment]
OK, I created a PR with the updated files in case this simple fix is sufficient, pending review from @Volker-E .

**Comment by prtksxna** [comment]
Hey @Nikerabbit  Could you confirm that you're seeing the same issue with other images that have text in them too:
https://design.wikimedia.org/style-guide/img/components/buttons_designing.svg
https://design.wikimedia.org/style-guide/img/components/buttons_quiet_states.svg
https://design.wikimedia.org/style-guide/img/components/buttons_toggle_intro.svg

**Comment by Nikerabbit** [comment]
DejaVu Serif. I don't see separate option for sans-serif, but I guess it would be DejaVu Sans.

**Comment by rinkydevi** [comment]
I can contribute in this issue,how can i proceed?

**Comment by golu098** [comment]
i want to contribute in your project grant me access as well as permission

**Comment by myself-Rishi-saha** [comment]
i want to work on this issue please assign me this issue.

**Comment by niket2219** [comment]
I can fix this issue so please assign me this issue..

**Comment by draunger** [comment]
Assign me

**Comment by Volker-E** [comment]
Please note, that the Design Style Guide is deprecated in favor of its successor [Codex, Design System for Wikimedia](https://doc.wikimedia.org/codex/latest/).
Nonetheless, in the new documentation the SVG on Linux issue should also have been fixed due to a different font family definition. In case there are remaining issues, please [file a task in Wikimedia bug tracker Phabricator](https://phabricator.wikimedia.org/maniphest/task/edit/form/37/?title=%5BREQUEST%5D&projects=codex&priority=triage&description=**What%20teams%20or%20group%20is%20this%20for%3F**%0A%0A**Who%20is%20your%20main%20point%20of%20contact%20and%20contact%20preference%3F**%0A%0A**What%20are%20the%20details%20of%20your%20request%3F%20Include%20relevant%20timelines%20or%20deadlines**%0A%0A**How%20does%20the%20request%20fit%20within%20departmental%20or%20foundation%20priorities%3F**%0A%0A**Is%20this%20request%20urgent%20or%20time-sensitive%3F**).
